# CMake toolchain file for cross-compiling to samwise (aarch64)
#
# Usage:
#   cmake -DCMAKE_TOOLCHAIN_FILE=<repo>/toolchains/cmake/samwise-aarch64.cmake ..
#
# The sysroot must be generated from a tested platform image via export-sdk.sh

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
set(CMAKE_AR aarch64-linux-gnu-ar)
set(CMAKE_STRIP aarch64-linux-gnu-strip)
set(CMAKE_LINKER aarch64-linux-gnu-ld)

# Sysroot: set to the SDK sysroot generated by export-sdk.sh
# Override with -DCMAKE_SYSROOT=<path> if needed
if(NOT DEFINED CMAKE_SYSROOT)
    get_filename_component(_TOOLCHAIN_DIR "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
    set(CMAKE_SYSROOT "${_TOOLCHAIN_DIR}/sysroot")
endif()

if(NOT EXISTS "${CMAKE_SYSROOT}/usr/include")
    message(WARNING "Sysroot not found at ${CMAKE_SYSROOT}. "
                    "Run export-sdk.sh to generate it from a tested image.")
endif()

# Search paths: find programs on host, everything else in sysroot
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# pkg-config: restrict to sysroot
set(ENV{PKG_CONFIG_PATH} "${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
